### ISSUE TITLE
Can't Download Videos After Upgrade

### ISSUE THREAD

**Issue by AaronKnowls** [z1nc0r3/AnyVideo-Downloader-Flow-Plugin#16] opened 2024-11-07 10:14 UTC
I just downloaded a video, found out about the upgrade, upgraded it, and I'm no longer able to download videos (I had to allowed internet connection to python that wasn't needed before, and also restarted Flow Launcher).

The results show up, but when I select one of them, the command prompt appears, shows errors and shuts down without any downloads.

In any case, thank you so much for this very useful plugin.

**Comment by z1nc0r3** [comment] 2024-11-07 20:44
@AaronKnowls Thank you for creating this issue. 
There are a few bugs when executing the download command due to a path error. I'm currently working on a fix and a new release will be released soon.

_If you are familiar with using pip, I think you can install `yt-dlp` package globally to fix this issue temporarily_
_`pip install yt-dlp`_

**Comment by Perseus333** [comment] 2024-11-08 17:02
> I think you can install yt-dlp package globally to fix this issue temporarily
pip install yt-dlp

I can confirm that this worked for me. Although I used `pipx install yt-dlp` and then `pipx ensurepath`, then I restarted flow launcher.

Now works flawlesly!

**Closed** 2024-11-14 22:23 UTC
Labels: bug
